# Generated by Django 2.2.6 on 2019-10-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Sayur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sayur', models.CharField(max_length=200)),
                ('ketinggian_min', models.CharField(max_length=50)),
                ('ketinggian_max', models.CharField(max_length=50)),
                ('deskripsi', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='files')),
            ],
        ),
    ]
